package services

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"io"
)

// EncryptionService handles encryption and decryption of data
type EncryptionService struct{}

// NewEncryptionService creates a new encryption service
func NewEncryptionService() *EncryptionService {
	return &EncryptionService{}
}

// EncryptData encrypts data using AES-256-GCM with a provided key
// Returns: encrypted data, nonce, error
func (e *EncryptionService) EncryptData(data []byte, key []byte) ([]byte, []byte, error) {
	// Derive a 32-byte key from the provided key using SHA-256
	keyHash := sha256.Sum256(key)
	derivedKey := keyHash[:]

	// Create AES cipher
	block, err := aes.NewCipher(derivedKey)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create cipher: %w", err)
	}

	// Create GCM
	aesGCM, err := cipher.NewGCM(block)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create GCM: %w", err)
	}

	// Generate nonce
	nonce := make([]byte, aesGCM.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, nil, fmt.Errorf("failed to generate nonce: %w", err)
	}

	// Encrypt data
	ciphertext := aesGCM.Seal(nil, nonce, data, nil)

	return ciphertext, nonce, nil
}

// DecryptData decrypts data using AES-256-GCM with a provided key and nonce
func (e *EncryptionService) DecryptData(encryptedData []byte, key []byte, nonce []byte) ([]byte, error) {
	// Derive a 32-byte key from the provided key using SHA-256
	keyHash := sha256.Sum256(key)
	derivedKey := keyHash[:]

	// Create AES cipher
	block, err := aes.NewCipher(derivedKey)
	if err != nil {
		return nil, fmt.Errorf("failed to create cipher: %w", err)
	}

	// Create GCM
	aesGCM, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("failed to create GCM: %w", err)
	}

	// Decrypt data
	plaintext, err := aesGCM.Open(nil, nonce, encryptedData, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt: %w", err)
	}

	return plaintext, nil
}

// DeriveKeyFromAddress derives an encryption key from a user's address and optional salt
// This creates a deterministic key that can be regenerated by the user
func DeriveKeyFromAddress(address string, salt []byte) []byte {
	// Combine address and salt
	data := append([]byte(address), salt...)
	// Hash to get a deterministic key
	keyHash := sha256.Sum256(data)
	return keyHash[:]
}

// EncodeEncryptionMetadata encodes encryption metadata (nonce) to base64 for storage
func EncodeEncryptionMetadata(nonce []byte) string {
	return base64.StdEncoding.EncodeToString(nonce)
}

// DecodeEncryptionMetadata decodes encryption metadata from base64
func DecodeEncryptionMetadata(encoded string) ([]byte, error) {
	return base64.StdEncoding.DecodeString(encoded)
}

// EncryptCSVData encrypts CSV data (as bytes) and returns encrypted data + metadata
func (e *EncryptionService) EncryptCSVData(csvBytes []byte, encryptionKey []byte) ([]byte, string, error) {
	encrypted, nonce, err := e.EncryptData(csvBytes, encryptionKey)
	if err != nil {
		return nil, "", err
	}
	metadata := EncodeEncryptionMetadata(nonce)
	return encrypted, metadata, nil
}

// DecryptCSVData decrypts CSV data using key and metadata
func (e *EncryptionService) DecryptCSVData(encryptedData []byte, encryptionKey []byte, metadata string) ([]byte, error) {
	nonce, err := DecodeEncryptionMetadata(metadata)
	if err != nil {
		return nil, fmt.Errorf("failed to decode metadata: %w", err)
	}
	return e.DecryptData(encryptedData, encryptionKey, nonce)
}

